# Analisa Machine Learning Data Lulusan

## Import Data Lulusan

In [46]:
import pandas as pd
import numpy as np
import chardet
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
file = 'data_lulusan.csv'

import pandas as pd
df = pd.read_csv('data_lulusan.csv')
df

IPK  \
0     2.49   
1     3.01   
2     3.07   
3     2.78   
4     2.92   
...    ...   
1269  3.28   
1270  3.03   
1271  3.53   
1272  3.09   
1273  3.10   

       Pengetahuan di bidang atau disiplin ilmu anda                                         (rendah)1-5(tinggi)  \
0                                                     5                                                            
1                                                     5                                                            
2                                                     5                                                            
3                                                     5                                                            
4                                                     5                                                            
...                                                 ...                                                            
1269                                                  5                                                            
1270                                                  4                                                            
1271                                                  4                                                            
1272                                                  5                                                            
1273                                                  5                                                            

      Pengetahuan di luar bidang atau disiplin ilmu anda        (rendah)1-5(tinggi)  \
0                                                     5                               
1                                                     5                               
2                                                     5                               
3                                                     5                               
4                                                     5                               
...                                                 ...                               
1269                                                  5                               
1270                                                  5                               
1271                                                  4                               
1272                                                  5                               
1273                                                  5                               

      Pengetahuan umum                  (rendah)1-5(tinggi)  \
0                                                     5       
1                                                     5       
2                                                     5       
3                                                     5       
4                                                     5       
...                                                 ...       
1269                                                  5       
1270                                                  5       
1271                                                  5       
1272                                                  5       
1273                                                  5       

      Ketrampilan internet                          (rendah)1-5(tinggi)  \
0                                                     5                   
1                                                     5                   
2                                                     5                   
3                                                     5                   
4                                                     5                   
...                                                 ...                   
1269                                                  5                   
1270                                       

## Distribusi Label
Label pada data ini ada pada kolom Posisi Pekerjaan dan akan dirubah menjadi kolom label untuk dipisahkan

In [47]:
df = df.rename(columns = {'Posisi Pekerjaan': 'label'})
df['label'].value_counts()

System administrator    214
Programmer              113
EDP Operator             97
Operator Komputer        56
Staff IT                 54
Web Designer             52
Technical engineer       51
Software engineer        48
Staff Administrasi       47
IT Support               46
Teknik Mesin             45
Sekretaris               42
IT Quality Control       41
Networking engineer      41
Sistem analis            39
Design Grafis            36
Digital Marketing        36
Call Centre              36
Staff IT Network         34
MIS Director             30
Web Programmer           29
Recepsionist             23
Customer Service         21
Sales                    16
Agent Monitoring ATM     15
Guru TIK                 12
Name: label, dtype: int64

## Label Encoding

Label encoding mengubah setiap nilai alfabetik dalam kolom menjadi angka yang berurutan

In [48]:
from sklearn.preprocessing import LabelEncoder
le_posisi_pekerjaan = LabelEncoder()
le_posisi_pekerjaan.fit(df["label"].astype(str))

df['label'] = le_posisi_pekerjaan.transform(df["label"].astype(str))

## Membagi Data menjadi Set Pelatihan dan Pengujian

Untuk menilai prediksi kita, kita perlu menggunakan satu set pelatihan dan pengujian. Model tersebut belajar dari data pelatihan dan kemudian membuat prediksi pada data pengujian. Karena kami memiliki jawaban yang benar untuk data pengujian, kami dapat mengetahui seberapa baik model dapat menggeneralisasi ke data baru. Penting untuk hanya menggunakan set pengujian sekali, karena ini dimaksudkan sebagai perkiraan seberapa baik performa model pada data baru.

Kami akan menyimpan 20% contoh untuk pengujian.

In [49]:
from sklearn.model_selection import train_test_split

RSEED =50
# Extract the labels
Y = df['label']
X = df.iloc[:,:-1].values

# 20% examples in test data
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)


#### Imputasi nilai yang hilang

Kita akan mengisi nilai yang hilang dengan mean dari kolom. Penting untuk dicatat bahwa kita mengisi nilai yang hilang di set pengujian dengan mean kolom di data pelatihan. Ini diperlukan karena jika kita mendapatkan data baru, kita harus menggunakan data pelatihan untuk mengisi nilai yang hilang.

In [50]:
X_train.shape

(1019, 31)

In [51]:
X_test.shape

(255, 31)

## Random Forest

In [52]:
from sklearn.ensemble import RandomForestClassifier

# Create the model with 100 trees
rf_model = RandomForestClassifier(n_estimators=100)

# Fit on training data
rf_model.fit(X_train, y_train)

rf_predictions = rf_model.predict(X_test)
rf_probs = rf_model.predict_proba(X_test)[:, 1]


### Akurasi

In [53]:
print("Accuracy:",metrics.accuracy_score(y_test, rf_probs))

Accuracy: 0.03137254901960784


### Confussion Matrix

In [54]:
print(confusion_matrix(y_test, rf_probs))

[[ 2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 8  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 8  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 5  0  0  0  0  0  0  0  0  0  0  0  0

### Classification Report

In [55]:
print(classification_report(y_test, rf_probs))

              precision    recall  f1-score   support

           0       0.01      1.00      0.02         2
           1       1.00      1.00      1.00         6
           2       0.00      0.00      0.00         4
           3       0.00      0.00      0.00        11
           4       0.00      0.00      0.00        11
           5       0.00      0.00      0.00        18
           7       0.00      0.00      0.00         8
           8       0.00      0.00      0.00         7
           9       0.00      0.00      0.00         5
          10       0.00      0.00      0.00         8
          11       0.00      0.00      0.00        17
          12       0.00      0.00      0.00        21
          13       0.00      0.00      0.00         5
          14       0.00      0.00      0.00         2
          15       0.00      0.00      0.00        12
          16       0.00      0.00      0.00        11
          17       0.00      0.00      0.00        12
          18       0.00    

/Users/haviansyah/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Adaboost Classifier

In [56]:
from sklearn.ensemble import AdaBoostClassifier
# Create adaboost classifer object
abc = AdaBoostClassifier(n_estimators=50,
                         learning_rate=1)
# Train Adaboost Classifer
abc_model = abc.fit(X_train, y_train)

#Predict the response for test dataset
abc_pred = abc_model.predict(X_test)

### Akurasi

In [57]:
print("Accuracy:",metrics.accuracy_score(y_test, abc_pred))

Accuracy: 0.8627450980392157


### Confussion Matrix

In [58]:
print(confusion_matrix(y_test, et_pred))

[[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 2 2 0 0 2 0 0 0 0 0 4 0 1 0 0]
 [0 1 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 1 0 0 0 4 0 0 0 0]
 [0 1 0 0 0 1 0 1 1 1 1 2 3 0 0 0 1 0 0 2 0 3 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1]
 [0 0 0 0 1 1 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 1 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 1 0 0 3 0 0 0 0]
 [0 0 0 0 0 1 0 0 1 0 1 1 2 1 0 0 0 0 0 4 0 2 0 4 0 0]
 [0 0 1 1 1 1 0 2 0 1 0 1 0 0 0 0 2 0 2 0 0 5 2 2 0 0]
 [0 0 0 0 0 0 0 0 2 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0]
 [1 0 0 1 1 0 0 2 0 0 0 0 2 0 0 0 1 0 1 0 1 1 1 0 0 0]
 [0 0 0 1 0 1 0 0 0 0 0 0 3 0 0 1 0 0 2 0 0 1 0 1 1 0]
 [0 0 0 0 0 0 0 1 0 0 0 1 3 1 0 0 1 0 0 0 0 3 0 0 2 0]
 [0 0 1 0 

### Classification Report

In [59]:
print(classification_report(y_test, abc_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       1.00      1.00      1.00         6
           2       0.00      0.00      0.00         4
           3       0.00      0.00      0.00        11
           4       0.50      1.00      0.67        11
           5       1.00      1.00      1.00        18
           7       0.42      1.00      0.59         8
           8       1.00      1.00      1.00         7
           9       0.00      0.00      0.00         5
          10       1.00      1.00      1.00         8
          11       1.00      1.00      1.00        17
          12       1.00      1.00      1.00        21
          13       1.00      1.00      1.00         5
          14       0.00      0.00      0.00         2
          15       0.48      1.00      0.65        12
          16       0.00      0.00      0.00        11
          17       1.00      1.00      1.00        12
          18       1.00    

/Users/haviansyah/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Extra Trees Classifier


In [60]:
from sklearn.ensemble import ExtraTreesClassifier
# Create adaboost classifer object
et = ExtraTreesClassifier()
# Train Adaboost Classifer
et_model = et.fit(X_train, y_train)

#Predict the response for test dataset
et_pred = et_model.predict(X_test)

### Akurasi

In [61]:
print("Accuracy:",metrics.accuracy_score(y_test, et_pred))

Accuracy: 1.0


### Confussion Matrix

In [62]:
print(confusion_matrix(y_test, et_pred))

[[ 2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0 11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0 11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  5

### Classification Report

In [63]:
print(classification_report(y_test, et_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         6
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00        11
           4       1.00      1.00      1.00        11
           5       1.00      1.00      1.00        18
           7       1.00      1.00      1.00         8
           8       1.00      1.00      1.00         7
           9       1.00      1.00      1.00         5
          10       1.00      1.00      1.00         8
          11       1.00      1.00      1.00        17
          12       1.00      1.00      1.00        21
          13       1.00      1.00      1.00         5
          14       1.00      1.00      1.00         2
          15       1.00      1.00      1.00        12
          16       1.00      1.00      1.00        11
          17       1.00      1.00      1.00        12
          18       1.00    

# Gradient Boosting Classifier

In [64]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier()
gb_model = gb.fit(X_train, y_train)
gb_pred = gb_model.predict(X_test)

### Akurasi


In [65]:
print("Accuracy:",metrics.accuracy_score(y_test, gb_pred))

Accuracy: 1.0


### Confussion Matrix

In [66]:
print(confusion_matrix(y_test, gb_pred))

[[ 2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0 11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0 11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  5

### Classification Report

In [67]:
print(classification_report(y_test, gb_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         6
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00        11
           4       1.00      1.00      1.00        11
           5       1.00      1.00      1.00        18
           7       1.00      1.00      1.00         8
           8       1.00      1.00      1.00         7
           9       1.00      1.00      1.00         5
          10       1.00      1.00      1.00         8
          11       1.00      1.00      1.00        17
          12       1.00      1.00      1.00        21
          13       1.00      1.00      1.00         5
          14       1.00      1.00      1.00         2
          15       1.00      1.00      1.00        12
          16       1.00      1.00      1.00        11
          17       1.00      1.00      1.00        12
          18       1.00    